name: Firts workflow
on: push
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Print Hello World
          run: |
            echo "Hello World"
            echo "This is my first workflow"